Links to static content
CenterForDigitalHumanities/TPEN-NL pull request #74
Opened 2021-07-13 13:59 UTC by thehabes

2021-07-14 14:09 UTC, cubap requested changes
I think there is just a missing commit so far, but most of this is good.

2021-07-14 14:09 UTC, cubap commented on web/js/newberry.js
> +            utlID = currentCanvasID.substring(currentCanvasID.lastIndexOf("paleography:"), currentCanvasID.length - 1).replace("paleography:", "");
I thought we wanted the first Index, it is just the case that for now we only have one match. Also, you may want a regex pattern for the match so we get only what we are expecting if there is a weird change.

At any rate, I think the `.replace` is excessive and you may just want `lastIndexOf()+12` instead

2021-07-14 14:09 UTC, cubap commented on web/js/newberry.js
> +                iframeDirectLink = buildIframeDirectLink("essay/" + utlID + ".md");
nope. you made this change already but haven't pushed it up.

2021-07-16 18:18 UTC, thehabes commented on web/italianTranscription.html
> +                <iframe class="loadingIframe" data_src="TODO?response_type=embed"></iframe>
Ah shoot I forgot I had been tempted to do both of these at the  same time, and so real early on I actually made some changes on this page.  They are correct at least...do you want me to undo these or keep them?

2021-07-20 14:50 UTC, cubap approved these changes

2021-07-20 14:50 UTC, merged